version: "3.8"

services:
  server-1:
    build: ./simulated_server
    container_name: server-1
    ports:
      - "8081:80"
    networks:
      - ga-network
    environment:
      - TRAFFIC_CAP=25
      - BASE_LATENCY=40

  server-2:
    build: ./simulated_server
    container_name: server-2
    ports:
      - "8082:80"
    networks:
      - ga-network
    environment:
      - TRAFFIC_CAP=35
      - BASE_LATENCY=25

  server-3:
    build: ./simulated_server
    container_name: server-3
    ports:
      - "8083:80"
    networks:
      - ga-network
    environment:
      - TRAFFIC_CAP=50
      - BASE_LATENCY=12

  optimizer:
    build: ./ga_controller
    container_name: ga-controller
    depends_on:
      - server-1
      - server-2
      - server-3
    networks:
      - ga-network
    volumes:
      - ./ga_controller:/app/ga_controller

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - server-1
      - server-2
      - server-3
    networks:
      - ga-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      
    depends_on:
      - prometheus
    networks:
      - ga-network

  load-driver:
    build: ./load_driver
    container_name: load-driver
    depends_on:
      - server-1
      - server-2
      - server-3
    networks:
      - ga-network

volumes:
  grafana-storage:
  prometheus-storage:

networks:
  ga-network:
    driver: bridge
