global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "servers"
    static_configs:
      - targets: ["server-1:80", "server-2:80", "server-3:80"]
    metrics_path: "/metrics"
    scheme: "http"
    scrape_interval: 5s
    scrape_timeout: 3s
