servers:
  - http://server-1:80/serve
  - http://server-2:80/serve
  - http://server-3:80/serve

ga:
  generations: 30
  population_size: 10
  parents_mating: 4
  mutation_percent: 30

weights:
  latency: 0.1
  throughput: 0.7
  error_rate: 0.1
  load_variance: 0.1

timeout: 2
